# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 050066493c9627c4476afa3cb6846898d97ae4a23e472bb7c8b103fbdf61f5af211a52a7cb7d03c63aca023b3184de5a662aad47e5bb5e6c8581def69904a79c

test:
  secret_key_base: 0c0296470a5c5b7147cda36712ec312fb104240c0effc877a5db7c430a260ce5589fa6615399e689671a529a316465aa496e7414370bbcd97e3f027a04fb3c4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
